# Generated by Django 4.2.27 on 2026-01-30 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox", "0002_drop_orphan_tenant_tree"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
