# Generated by Django 4.2.27 on 2026-01-30 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox", "0003_tenant"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tenant",
        ),
    ]
