# Generated by Django 4.2.27 on 2026-01-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox", "0004_delete_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantgroup",
            name="node_type",
            field=models.CharField(
                choices=[("group", "Group"), ("tenant", "Tenant")],
                default="group",
                max_length=10,
            ),
        ),
    ]
