# Generated by Django 4.2.27 on 2026-01-30 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
        ("sandbox", "0005_tenantgroup_node_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantgroup",
            name="account",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenant_group_roots",
                to="tenants.account",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenantgroup",
            name="tree_label",
            field=models.CharField(
                blank=True,
                help_text="Label for the tree root. Only used for root nodes.",
                max_length=255,
                null=True,
            ),
        ),
    ]
