# Generated by Django 4.2.27 on 2026-01-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox", "0006_tenantgroup_account_tenantgroup_tree_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantgroup",
            name="group_type",
            field=models.CharField(
                choices=[
                    ("billing", "Account / Billing Group"),
                    ("data-feed", "Data Feed Group (e.g. for multi-tenant data feed)"),
                    ("operating", "Operating Group (e.g. a Dealer Group)"),
                    ("regional", "Regional Group (e.g. for NSC)"),
                    ("rooftop", "Multiple brands at a single physical location"),
                    (
                        "call-centre",
                        "Call Centre (e.g. some brands for the rooftop or multi location)",
                    ),
                ],
                default="operating",
                help_text="Type of this group",
                max_length=20,
            ),
        ),
    ]
