# Generated by Django 4.2.27 on 2026-02-01 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_rename_live_tenant_is_live"),
        ("sandbox", "0007_tenantgroup_group_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantgroup",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this node represents a tenant (leaf node).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_nodes",
                to="tenants.tenant",
            ),
        ),
    ]
