# Generated by Django 4.2.27 on 2026-02-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox", "0008_tenantgroup_tenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantgroup",
            name="node_type",
            field=models.CharField(
                choices=[("root", "Root"), ("group", "Group"), ("tenant", "Tenant")],
                default="group",
                max_length=10,
            ),
        ),
    ]
