# Generated by Django 4.2.27 on 2026-02-01 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox", "0009_alter_tenantgroup_node_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tenantgroup",
            old_name="tree_label",
            new_name="root_label",
        ),
    ]
