# Generated by Django 4.2.27 on 2026-02-01 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox", "0010_rename_tree_label_tenantgroup_root_label"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tenantgroup",
            old_name="name",
            new_name="group_label",
        ),
    ]
