# Generated by Django 4.2.27 on 2026-02-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox", "0011_rename_name_tenantgroup_group_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantgroup",
            name="group_label",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
