# Generated by Django 4.2.27 on 2026-02-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sandbox", "0012_alter_tenantgroup_group_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantgroup",
            name="ftp_drop_folder_path",
            field=models.CharField(
                blank=True,
                help_text="Path of sFTP drop folder from this platform",
                max_length=255,
                null=True,
            ),
        ),
    ]
