# Generated by Django 5.2.10 on 2026-01-15 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0004_alter_tenant_internal_tenant_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_customer_id",
                    models.CharField(
                        help_text="Customer identifier from source system",
                        max_length=100,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="e.g. Mr, Mrs, Ms, Dr", max_length=20
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "salutation",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Dear John', 'Dear Mr Smith'",
                        max_length=150,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True, help_text="Mobile phone number", max_length=30
                    ),
                ),
                (
                    "home_phone",
                    models.CharField(
                        blank=True, help_text="Home phone number", max_length=30
                    ),
                ),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("address_line_3", models.CharField(blank=True, max_length=255)),
                ("address_line_4", models.CharField(blank=True, max_length=255)),
                ("address_line_5", models.CharField(blank=True, max_length=255)),
                (
                    "postcode",
                    models.CharField(blank=True, help_text="Postcode", max_length=20),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "contract_customer",
                "indexes": [
                    models.Index(
                        fields=["tenant", "external_customer_id"],
                        name="contract_cu_tenant__34c84c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "external_customer_id"),
                        name="uniq_customer_per_tenant",
                    )
                ],
            },
        ),
    ]
