# Generated by Django 4.2.27 on 2026-01-24 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_retailer_id",
                    models.CharField(
                        help_text="Retailer identifier from source system",
                        max_length=100,
                    ),
                ),
                (
                    "external_customer_id",
                    models.CharField(
                        help_text="Customer identifier from source system",
                        max_length=100,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="e.g. Mr, Mrs, Ms, Dr", max_length=20
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                (
                    "salutation",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Dear John', 'Dear Mr Smith'",
                        max_length=150,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "mobile_phone",
                    models.CharField(
                        blank=True, help_text="Mobile phone number", max_length=30
                    ),
                ),
                (
                    "home_phone",
                    models.CharField(
                        blank=True, help_text="Home phone number", max_length=30
                    ),
                ),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("address_line_3", models.CharField(blank=True, max_length=255)),
                ("address_line_4", models.CharField(blank=True, max_length=255)),
                ("address_line_5", models.CharField(blank=True, max_length=255)),
                (
                    "postcode",
                    models.CharField(blank=True, help_text="Postcode", max_length=20),
                ),
                (
                    "mobile_opt_in_value",
                    models.CharField(
                        choices=[
                            ("true", "True"),
                            ("false", "False"),
                            ("unspecified", "Unspecified"),
                            ("missing", "Missing"),
                        ],
                        default="missing",
                        help_text="The customer opted in or out of receiving marketing via their mobile phone number: True, False, or Unspecified",
                        max_length=12,
                        verbose_name="Tri-state flag",
                    ),
                ),
                (
                    "mobile_opt_in_date",
                    models.DateField(
                        blank=True,
                        help_text="The date the customer last opted in or out of receiving marketing via their mobile phone number",
                        null=True,
                        verbose_name="Mobile op-in date",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "contract_customer",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_retailer_id",
                    models.CharField(
                        help_text="Retailer identifier from source system",
                        max_length=20,
                    ),
                ),
                (
                    "external_vehicle_id",
                    models.CharField(
                        help_text="Vehicle unique identifier (number) from source system",
                        max_length=20,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Vehicle number from source system", max_length=20
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(
                        blank=True,
                        help_text="The date the vehicle was first registered",
                        null=True,
                        verbose_name="Registration date",
                    ),
                ),
                (
                    "vin",
                    models.CharField(help_text="VIN from source system", max_length=20),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True, help_text="e.g. PETROL", max_length=20
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "contract_vehicle",
                "indexes": [
                    models.Index(
                        fields=["tenant", "external_vehicle_id"],
                        name="contract_ve_tenant__b7c607_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                fields=("tenant", "external_vehicle_id"), name="uniq_vehicle_per_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "external_customer_id"],
                name="contract_cu_tenant__34c84c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("tenant", "external_customer_id"),
                name="uniq_customer_per_tenant",
            ),
        ),
    ]
