# Generated by Django 4.2.27 on 2026-02-08 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email_opt_in_date",
            field=models.DateField(
                blank=True,
                help_text="The date the customer last opted in or out of receiving marketing via their email",
                null=True,
                verbose_name="Mobile op-in date",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="email_opt_in_value",
            field=models.CharField(
                choices=[
                    ("true", "True"),
                    ("false", "False"),
                    ("unspecified", "Unspecified"),
                    ("missing", "Missing"),
                ],
                default="missing",
                help_text="The customer opted in or out of receiving marketing via email: True, False, or Unspecified",
                max_length=12,
                verbose_name="Tri-state flag",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="home_phone_opt_in_date",
            field=models.DateField(
                blank=True,
                help_text="The date the customer last opted in or out of receiving marketing via their home phone number",
                null=True,
                verbose_name="Mobile op-in date",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="home_phone_opt_in_value",
            field=models.CharField(
                choices=[
                    ("true", "True"),
                    ("false", "False"),
                    ("unspecified", "Unspecified"),
                    ("missing", "Missing"),
                ],
                default="missing",
                help_text="The customer opted in or out of receiving marketing via their home phone number: True, False, or Unspecified",
                max_length=12,
                verbose_name="Tri-state flag",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="brand",
            field=models.CharField(blank=True, help_text="e.g. BMW", max_length=20),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="model",
            field=models.CharField(blank=True, help_text="e.g. 118d", max_length=20),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="variant",
            field=models.CharField(blank=True, help_text="e.g. 1D31A8", max_length=20),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(blank=True, help_text="e.g. DIESEL", max_length=20),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(help_text="VIN from source system", max_length=17),
        ),
    ]
