# Generated by Django 5.2.10 on 2026-01-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="external_retailer_id",
            field=models.CharField(
                default="",
                help_text="Retailer identifier from source system",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
