# Generated by Django 5.2.10 on 2026-01-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0002_customer_external_retailer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="mobile_opt_in_date",
            field=models.DateField(
                blank=True,
                help_text="The date the customer last opted in or out of receiving marketing via their mobile phone number",
                null=True,
                verbose_name="Mobile op-in date",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="mobile_opt_in_value",
            field=models.CharField(
                choices=[
                    ("true", "True"),
                    ("false", "False"),
                    ("unspecified", "Unspecified"),
                    ("missing", "Missing"),
                ],
                default="missing",
                help_text="The customer opted in or out of receiving marketing via their mobile phone number: True, False, or Unspecified",
                max_length=12,
                verbose_name="Tri-state flag",
            ),
        ),
    ]
