# Generated by Django 4.2.27 on 2026-03-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0002_customer_email_opt_in_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
