# Generated by Django 5.2.10 on 2026-01-18 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0003_customer_mobile_opt_in_date_and_more"),
        ("tenants", "0004_alter_tenant_internal_tenant_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_retailer_id",
                    models.CharField(
                        help_text="Retailer identifier from source system",
                        max_length=20,
                    ),
                ),
                (
                    "external_vehicle_id",
                    models.CharField(
                        help_text="Vehicle unique identifier (number) from source system",
                        max_length=20,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Vehicle number from source system", max_length=20
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(
                        blank=True,
                        help_text="The date the vehicle was first registered",
                        null=True,
                        verbose_name="Registration date",
                    ),
                ),
                (
                    "vin",
                    models.CharField(help_text="VIN from source system", max_length=20),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True, help_text="e.g. PETROL", max_length=20
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "contract_vehicle",
                "indexes": [
                    models.Index(
                        fields=["tenant", "external_vehicle_id"],
                        name="contract_ve_tenant__b7c607_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "external_vehicle_id"),
                        name="uniq_vehicle_per_tenant",
                    )
                ],
            },
        ),
    ]
