# Generated by Django 4.2.27 on 2026-03-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0003_customer_deleted_vehicle_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="postcode",
        ),
        migrations.AddField(
            model_name="customer",
            name="postcode_area",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="customer",
            name="postcode_district",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name="customer",
            name="postcode_full",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="customer",
            name="postcode_sector",
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
