# Generated by Django 4.2.27 on 2026-03-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0005_alter_customer_address_line_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="deleted",
        ),
        migrations.AddField(
            model_name="customer",
            name="row_hash",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="row_hash",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
