# Generated by Django 4.2.27 on 2026-03-25 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0045_alter_accountjob_options"),
        ("contracts", "0006_remove_customer_deleted_remove_vehicle_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="account",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.account",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="account",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.account",
            ),
            preserve_default=False,
        ),
    ]
