# Generated by Django 4.2.27 on 2026-03-25 23:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0007_customer_account_vehicle_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="account",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="account",
        ),
    ]
