# Generated by Django 4.2.27 on 2026-03-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0008_remove_customer_account_remove_vehicle_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="external_customer_id",
            field=models.CharField(
                help_text="Customer identifier from source system", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="external_retailer_id",
            field=models.CharField(
                help_text="Retailer identifier from source system", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="external_retailer_id",
            field=models.CharField(
                help_text="Retailer identifier from source system", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="external_vehicle_id",
            field=models.CharField(
                help_text="Vehicle unique identifier (number) from source system",
                max_length=10,
            ),
        ),
    ]
