# Generated by Django 4.2.27 on 2026-03-27 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0045_alter_accountjob_options"),
        ("contracts", "0009_alter_customer_external_customer_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerVehicleLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_hash", models.CharField(max_length=64)),
                (
                    "external_customer_id",
                    models.CharField(
                        help_text="Customer unique identifier (number) from source system",
                        max_length=50,
                    ),
                ),
                (
                    "external_vehicle_id",
                    models.CharField(
                        help_text="Vehicle unique identifier (number) from source system",
                        max_length=10,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_vehicle_link",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "contract_customer_vehicle_link",
                "indexes": [
                    models.Index(
                        fields=["tenant", "external_customer_id"],
                        name="contract_cu_tenant__fd6d88_idx",
                    ),
                    models.Index(
                        fields=["tenant", "external_vehicle_id"],
                        name="contract_cu_tenant__79d800_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="customervehiclelink",
            constraint=models.UniqueConstraint(
                fields=("tenant", "external_customer_id", "external_vehicle_id"),
                name="uniq_customer_vehicle_per_tenant",
            ),
        ),
    ]
