# Generated by Django 4.2.27 on 2026-03-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0010_customervehiclelink_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=371),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=371),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address_line_3",
            field=models.CharField(blank=True, max_length=371),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address_line_4",
            field=models.CharField(blank=True, max_length=371),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address_line_5",
            field=models.CharField(blank=True, max_length=371),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=370, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(blank=True, max_length=164),
        ),
        migrations.AlterField(
            model_name="customer",
            name="home_phone",
            field=models.CharField(
                blank=True, help_text="Home phone number", max_length=71
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, max_length=164),
        ),
        migrations.AlterField(
            model_name="customer",
            name="mobile_phone",
            field=models.CharField(
                blank=True, help_text="Mobile phone number", max_length=71
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="postcode_area",
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AlterField(
            model_name="customer",
            name="postcode_district",
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name="customer",
            name="postcode_full",
            field=models.CharField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name="customer",
            name="postcode_sector",
            field=models.CharField(blank=True, max_length=39),
        ),
        migrations.AlterField(
            model_name="customer",
            name="salutation",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'Dear John', 'Dear Mr Smith'",
                max_length=231,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="title",
            field=models.CharField(
                blank=True, help_text="e.g. Mr, Mrs, Ms, Dr", max_length=58
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="registration_number",
            field=models.CharField(
                help_text="Vehicle number from source system", max_length=58
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(help_text="VIN from source system", max_length=54),
        ),
    ]
