# Generated by Django 4.2.27 on 2026-04-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0012_alter_customer_address_line_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="fingerprint_vehicle_reg",
            field=models.CharField(
                blank=True, help_text="Used in upstream data joins", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fingerprint_vin17",
            field=models.CharField(
                blank=True, help_text="Used in upstream data joins", max_length=64
            ),
        ),
    ]
