# Generated by Django 4.2.27 on 2026-04-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0013_vehicle_fingerprint_vehicle_reg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="fingerprint_postcode_area",
            field=models.CharField(
                blank=True, help_text="Used in upstream data joins", max_length=64
            ),
        ),
    ]
