# Generated by Django 4.2.27 on 2026-04-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0014_customer_fingerprint_postcode_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="fingerprint_postcode_district",
            field=models.CharField(
                blank=True, help_text="Used in upstream data joins", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="fingerprint_postcode_full",
            field=models.CharField(
                blank=True, help_text="Used in upstream data joins", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="fingerprint_postcode_sector",
            field=models.CharField(
                blank=True, help_text="Used in upstream data joins", max_length=64
            ),
        ),
    ]
