# Generated by Django 4.2.27 on 2026-04-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0015_customer_fingerprint_postcode_district_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle",
            old_name="fingerprint_vin17",
            new_name="fingerprint_vin",
        ),
        migrations.CreateModel(
            name="Recall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_hash", models.CharField(max_length=64)),
                (
                    "vin",
                    models.CharField(help_text="VIN from source system", max_length=68),
                ),
                ("code", models.CharField(help_text="Recall code", max_length=255)),
                ("desc", models.CharField(help_text="Description", max_length=255)),
                (
                    "fingerprint_vin",
                    models.CharField(
                        blank=True,
                        help_text="Used in upstream data joins",
                        max_length=64,
                    ),
                ),
            ],
            options={
                "db_table": "contract_recall",
                "indexes": [
                    models.Index(
                        fields=["vin", "code"], name="contract_re_vin_a6042e_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="recall",
            constraint=models.UniqueConstraint(
                fields=("fingerprint_vin", "code"), name="uniq_vin_code"
            ),
        ),
    ]
