# Generated by Django 4.2.27 on 2026-04-16 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0049_sftpdropzone_test_sftp_password_and_more"),
        ("contracts", "0016_rename_fingerprint_vin17_vehicle_fingerprint_vin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customervehiclelink",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customer_vehicle_links",
                to="tenants.tenant",
            ),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_hash", models.CharField(max_length=64)),
                (
                    "vin",
                    models.CharField(help_text="VIN from source system", max_length=68),
                ),
                (
                    "fingerprint_vin",
                    models.CharField(
                        blank=True,
                        help_text="Used in upstream data joins",
                        max_length=64,
                    ),
                ),
                (
                    "date_in",
                    models.DateField(
                        help_text="The date the customers vehicle is expected to arrive at the workshop",
                        verbose_name="Arrival date",
                    ),
                ),
                (
                    "external_customer_id",
                    models.CharField(
                        help_text="Customer unique identifier (number) from source system",
                        max_length=50,
                    ),
                ),
                (
                    "external_vehicle_id",
                    models.CharField(
                        help_text="Vehicle unique identifier (number) from source system",
                        max_length=10,
                    ),
                ),
                (
                    "booking_number",
                    models.IntegerField(
                        blank=True, help_text="Booking number", null=True
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "contract_booking",
                "indexes": [
                    models.Index(
                        fields=[
                            "tenant",
                            "external_customer_id",
                            "external_vehicle_id",
                            "date_in",
                            "booking_number",
                        ],
                        name="contract_bo_tenant__52a45d_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="booking",
            constraint=models.UniqueConstraint(
                fields=(
                    "tenant",
                    "external_customer_id",
                    "external_vehicle_id",
                    "date_in",
                    "booking_number",
                ),
                name="uniq_booking",
            ),
        ),
    ]
