# Generated by Django 4.2.27 on 2026-04-17 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0017_alter_customervehiclelink_tenant_booking_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="fingerprint_vin",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="vin",
        ),
    ]
