# Generated by Django 4.2.27 on 2026-01-24 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rls_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="RLS Key",
                    ),
                ),
                (
                    "internal_tenant_code",
                    models.CharField(
                        max_length=50, verbose_name="Internal (to palmTree) tenant code"
                    ),
                ),
                ("external_tenant_code", models.CharField(max_length=100)),
                ("desc", models.CharField(max_length=200)),
                ("logo_path", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TenantGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("operating", "Operating Group (e.g. a Dealer Group)"),
                            ("regional", "Regional Group (e.g. for NSC)"),
                            ("billing", "Billing Group"),
                            (
                                "system",
                                "System Group (e.g. for multi-tenant data feed)",
                            ),
                            (
                                "call_centre",
                                "Call Centre (e.g. some brands for the rooftop or multi location)",
                            ),
                            (
                                "rooftop",
                                "Multiple brands at a single physical location",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("tenants", models.ManyToManyField(to="tenants.tenant")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserTenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.tenant"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "tenant")},
            },
        ),
    ]
