# Generated by Django 5.2.10 on 2026-01-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("internal_tenant_code", models.CharField(max_length=50)),
                ("external_tenant_code", models.CharField(max_length=100)),
                ("desc", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
