# Generated by Django 4.2.27 on 2026-02-01 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tenant",
            old_name="live",
            new_name="is_live",
        ),
    ]
