# Generated by Django 5.2.10 on 2026-01-15 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_alter_tenant_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tenant",
            old_name="id",
            new_name="rls_key",
        ),
    ]
