# Generated by Django 4.2.27 on 2026-01-24 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_account_group_tenant_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tenants.group",
            ),
        ),
    ]
