# Generated by Django 4.2.27 on 2026-02-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_rename_live_tenant_is_live"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line_3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line_4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "address_line_5",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("postcode", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "internal_location_code",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
            ],
            options={
                "verbose_name": "UK Address",
                "verbose_name_plural": "UK Addresses",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="tenant",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.location",
            ),
        ),
    ]
