# Generated by Django 4.2.27 on 2026-01-24 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_alter_tenant_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tenants.group",
            ),
        ),
    ]
