# Generated by Django 4.2.27 on 2026-02-02 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_location_tenant_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="account",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.account",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tenant",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.location",
            ),
        ),
    ]
