# Generated by Django 5.2.10 on 2026-01-15 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0003_rename_id_tenant_rls_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="internal_tenant_code",
            field=models.CharField(
                max_length=50, verbose_name="Internal (to palmTree) tenant code"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="rls_key",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="RLS Key",
            ),
        ),
    ]
