# Generated by Django 4.2.27 on 2026-01-24 23:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_alter_tenant_group"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TenantGroup",
        ),
    ]
