# Generated by Django 4.2.27 on 2026-02-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0004_location_account_alter_tenant_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "Location", "verbose_name_plural": "Locations"},
        ),
        migrations.AlterField(
            model_name="tenant",
            name="internal_tenant_code",
            field=models.CharField(
                max_length=50,
                unique=True,
                verbose_name="Internal (to palmTree) tenant code",
            ),
        ),
    ]
