# Generated by Django 4.2.27 on 2026-02-02 20:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0005_alter_location_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Marque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("short", models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="short",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.account",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="internal_tenant_code",
            field=models.CharField(
                max_length=26,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(14)],
                verbose_name="Internal (to palmTree) tenant code made up of ACCOUNT_/LOCATION/BRAND___s",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tenants.location",
            ),
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("short", models.CharField(blank=True, max_length=8)),
                (
                    "marque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenants.marque"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tenant",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="tenants.brand",
            ),
        ),
    ]
