# Generated by Django 4.2.27 on 2026-01-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0006_group_group_type_tenant_live"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="group_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("billing", "Account / Billing Group"),
                    (
                        "data-feed",
                        "Data Feed Group (e.g. for multi-tenant data feed). Provides sFTP drop folder",
                    ),
                    ("operating", "Operating Group (e.g. a Dealer Group)"),
                    ("regional", "Regional Group (e.g. for NSC)"),
                    ("rooftop", "Multiple brands at a single physical location"),
                    (
                        "call-centre",
                        "Call Centre (e.g. some brands for the rooftop or multi location)",
                    ),
                ],
                help_text="Categorise the type of group",
                max_length=20,
            ),
        ),
    ]
