# Generated by Django 4.2.27 on 2026-02-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0006_marque_account_short_alter_tenant_account_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="location",
            old_name="internal_location_code",
            new_name="short",
        ),
        migrations.AlterField(
            model_name="tenant",
            name="internal_tenant_code",
            field=models.CharField(
                blank=True,
                help_text="Internal (to palmTree) tenant code made up of ACCOUNT/LOCATION/BRAND. Leave blank and I'll default for you",
                max_length=26,
                unique=True,
                verbose_name="Internal tenant code",
            ),
        ),
    ]
