# Generated by Django 4.2.27 on 2026-01-26 19:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0007_alter_group_group_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserTenant",
        ),
    ]
