# Generated by Django 4.2.27 on 2026-02-03 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0006_delete_tenantmapping"),
        ("tenants", "0008_tenantmapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.account",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="canonical.job"
                    ),
                ),
            ],
        ),
    ]
