# Generated by Django 4.2.27 on 2026-01-26 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0009_useraccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="account",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.account",
            ),
            preserve_default=False,
        ),
    ]
