# Generated by Django 4.2.27 on 2026-02-06 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0010_role_sftpdropzones"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SFTPDropZones",
        ),
    ]
