# Generated by Django 4.2.27 on 2026-02-06 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0011_delete_sftpdropzones"),
    ]

    operations = [
        migrations.CreateModel(
            name="SFTPDropZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sftp_parent_folder", models.CharField(max_length=50)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.account",
                    ),
                ),
            ],
        ),
    ]
