# Generated by Django 4.2.27 on 2026-02-06 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0012_sftpdropzone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sftpdropzone",
            options={
                "verbose_name": "sFTP drop zone",
                "verbose_name_plural": "sFTP drop zones",
            },
        ),
        migrations.AlterModelOptions(
            name="tenantmapping",
            options={
                "verbose_name": "Tenant code mapping",
                "verbose_name_plural": "Tenant code mappings",
            },
        ),
        migrations.AddField(
            model_name="accountjob",
            name="sftp_drop_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tenants.sftpdropzone",
            ),
        ),
    ]
