# Generated by Django 4.2.27 on 2026-02-06 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0013_alter_sftpdropzone_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountjob",
            name="tenant_mapping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tenants.tenantmapping",
            ),
        ),
        migrations.AlterField(
            model_name="accountjob",
            name="sftp_drop_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tenants.sftpdropzone",
                verbose_name="sFTP drop zone",
            ),
        ),
    ]
