# Generated by Django 4.2.27 on 2026-02-07 00:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0014_accountjob_tenant_mapping_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountjob",
            name="tenant_mapping",
        ),
        migrations.DeleteModel(
            name="TenantMapping",
        ),
    ]
