# Generated by Django 4.2.27 on 2026-02-07 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0015_remove_accountjob_tenant_mapping_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desc", models.CharField(max_length=200)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenants.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantMappingCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_system_field_value", models.CharField(max_length=255)),
                (
                    "effective_from_date",
                    models.DateField(help_text="The date the mapping is valid from"),
                ),
                (
                    "mapped_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mapping_codes_mapped_to_this_tenant",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "tenant_mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mapping_codes",
                        to="tenants.tenantmapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant mapping code",
                "verbose_name_plural": "Tenant mapping codes",
                "unique_together": {
                    (
                        "tenant_mapping",
                        "source_system_field_value",
                        "effective_from_date",
                    )
                },
            },
        ),
    ]
