# Generated by Django 4.2.27 on 2026-02-07 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0016_tenantmapping_tenantmappingcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountjob",
            name="tenant_mapping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tenants.tenantmapping",
            ),
        ),
    ]
