# Generated by Django 4.2.27 on 2026-02-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0017_accountjob_tenant_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="sftpdropzone",
            name="desc",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
