# Generated by Django 4.2.27 on 2026-02-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0007_alter_job_test_table"),
        ("tenants", "0018_sftpdropzone_desc"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountTableData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of rows, first row is header",
                    ),
                ),
                (
                    "table_data",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="account_table_data",
                        to="canonical.tabledata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account table data",
                "verbose_name_plural": "Account table data",
            },
        ),
    ]
