# Generated by Django 4.2.27 on 2026-02-07 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0019_accounttabledata"),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttabledata",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.account",
            ),
        ),
    ]
