# Generated by Django 4.2.27 on 2026-02-07 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0020_accounttabledata_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttabledata",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenants.account"
            ),
        ),
    ]
