# Generated by Django 4.2.27 on 2026-02-07 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0021_alter_accounttabledata_account"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accounttabledata",
            old_name="table_data",
            new_name="table_data_copied_from",
        ),
    ]
