# Generated by Django 4.2.27 on 2026-02-07 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0022_rename_table_data_accounttabledata_table_data_copied_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountjob",
            name="account_table_data",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tenants.accounttabledata",
            ),
        ),
    ]
