# Generated by Django 4.2.27 on 2026-02-11 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0023_accountjob_account_table_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountEncryption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encrypted_dek", models.BinaryField()),
                ("dek_kms_key_id", models.CharField(max_length=255)),
                (
                    "dek_algorithm",
                    models.CharField(default="AES-256-GCM", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.account",
                    ),
                ),
            ],
        ),
    ]
