# Generated by Django 4.2.27 on 2026-02-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0024_accountencryption"),
    ]

    operations = [
        migrations.AddField(
            model_name="sftpdropzone",
            name="scope",
            field=models.TextField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
