# Generated by Django 4.2.27 on 2026-02-19 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0025_sftpdropzone_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="SFTPDropZoneScopedTenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scoped_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scoped_tenants",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "sftp_drop_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.sftpdropzone",
                    ),
                ),
            ],
        ),
    ]
