# Generated by Django 4.2.27 on 2026-02-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0026_sftpdropzonescopedtenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="sftpdropzone",
            name="folder_path",
            field=models.CharField(default="", editable=False, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sftpdropzone",
            name="sftp_user",
            field=models.CharField(default="", editable=False, max_length=50),
            preserve_default=False,
        ),
    ]
