# Generated by Django 4.2.27 on 2026-02-24 22:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0027_sftpdropzone_folder_path_sftpdropzone_sftp_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sftpdropzone",
            options={},
        ),
        migrations.RenameField(
            model_name="sftpdropzone",
            old_name="sftp_parent_folder",
            new_name="zone_folder",
        ),
    ]
