# Generated by Django 4.2.27 on 2026-02-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0028_alter_sftpdropzone_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sftpdropzone",
            name="desc",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="sftpdropzone",
            name="scope",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
