# Generated by Django 4.2.27 on 2026-02-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0029_alter_sftpdropzone_desc_alter_sftpdropzone_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="sftpdropzone",
            name="retention_period_days",
            field=models.PositiveIntegerField(
                default=7,
                help_text="Number of days to keep files before automatic cleanup",
            ),
        ),
    ]
