# Generated by Django 4.2.27 on 2026-03-01 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0030_sftpdropzone_retention_period_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="brand",
        ),
        migrations.DeleteModel(
            name="Brand",
        ),
        migrations.DeleteModel(
            name="Marque",
        ),
    ]
