# Generated by Django 4.2.27 on 2026-03-01 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("global_data", "0001_initial"),
        ("tenants", "0031_remove_tenant_brand_delete_brand_delete_marque"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="global_data.brand",
            ),
        ),
    ]
