# Generated by Django 4.2.27 on 2026-03-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0032_tenant_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
