# Generated by Django 4.2.27 on 2026-03-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0034_account_created_at_account_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sftpdropzone",
            name="folder_path",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="sftpdropzone",
            name="sftp_user",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
