# Generated by Django 4.2.27 on 2026-03-04 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0017_canonicalfield_created_at_canonicalfield_deleted_and_more"),
        ("tenants", "0035_alter_sftpdropzone_folder_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounttabledata",
            name="table_data_copied_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="account_table_data",
                to="canonical.tabledata",
            ),
        ),
    ]
