# Generated by Django 4.2.27 on 2026-03-09 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0036_alter_accounttabledata_table_data_copied_from"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sftpdropzone",
            name="sftp_user",
        ),
    ]
