# Generated by Django 4.2.27 on 2026-03-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0037_remove_sftpdropzone_sftp_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="sftpdropzone",
            name="wait_time_before_ready_to_move",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Number of seconds to wait before moving files from /drop to /ready",
            ),
        ),
    ]
