# Generated by Django 4.2.27 on 2026-03-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0038_sftpdropzone_wait_time_before_ready_to_move"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountjob",
            name="auto_or_manual",
            field=models.CharField(
                choices=[
                    ("auto", "Automated (started by background task runner)"),
                    ("manual", "Manual (start via this page)"),
                ],
                default="auto",
                max_length=6,
            ),
        ),
    ]
