# Generated by Django 4.2.27 on 2026-03-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0039_accountjob_auto_or_manual"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountjob",
            name="auto_or_manual",
            field=models.CharField(
                choices=[
                    ("auto", "Automated (started by background task runner)"),
                    ("manual", "Manual (start via this admin page)"),
                ],
                default="auto",
                max_length=6,
            ),
        ),
    ]
