# Generated by Django 4.2.27 on 2026-03-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0040_alter_accountjob_auto_or_manual"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountjob",
            name="move_source_file_on_completion",
            field=models.BooleanField(
                default=True,
                help_text="Move the source file from /ready to /processed folder? (If it required by another job then leave unticked)",
            ),
        ),
    ]
