# Generated by Django 4.2.27 on 2026-03-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0041_accountjob_move_source_file_on_completion"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountjob",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="accountjob",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=1, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
