# Generated by Django 4.2.27 on 2026-03-20 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0042_alter_accountjob_options_accountjob_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountjob",
            options={},
        ),
        migrations.RemoveField(
            model_name="accountjob",
            name="order",
        ),
    ]
