# Generated by Django 4.2.27 on 2026-03-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0043_alter_accountjob_options_remove_accountjob_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountjob",
            name="order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
