# Generated by Django 4.2.27 on 2026-03-24 20:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0044_accountjob_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountjob",
            options={"ordering": ["order"]},
        ),
    ]
