# Generated by Django 4.2.27 on 2026-04-08 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0045_alter_accountjob_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountJobLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("completed_datetime", models.DateTimeField(auto_now_add=True)),
                ("result_text", models.CharField(max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.account",
                    ),
                ),
                (
                    "accountjob",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.accountjob",
                    ),
                ),
            ],
            options={
                "ordering": ["completed_datetime"],
            },
        ),
    ]
