# Generated by Django 4.2.27 on 2026-04-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0046_accountjoblog"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountjoblog",
            name="path_and_filename",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
