# Generated by Django 4.2.27 on 2026-04-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0048_alter_accountjoblog_result_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="sftpdropzone",
            name="test_sftp_password",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sftpdropzone",
            name="test_sftp_user",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
