# Generated by Django 4.2.27 on 2026-04-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0049_sftpdropzone_test_sftp_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountjob",
            name="filename_prefix",
            field=models.CharField(default="tbc", max_length=100),
            preserve_default=False,
        ),
    ]
