# Generated by Django 4.2.27 on 2026-04-17 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0050_accountjob_filename_prefix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountjob",
            name="filename_prefix",
        ),
    ]
