# Generated by Django 4.2.27 on 2026-04-23 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0051_remove_accountjob_filename_prefix"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountjoblog",
            name="sftpdropzone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenants.sftpdropzone",
            ),
        ),
    ]
