# Generated by Django 4.2.27 on 2026-04-23 21:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0052_accountjoblog_sftpdropzone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountjoblog",
            name="sftpdropzone",
        ),
    ]
