# Generated by Django 4.2.27 on 2026-04-23 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0054_accountjoblog_sftpdropzone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountjoblog",
            old_name="sftpdropzone",
            new_name="sftp_drop_zone",
        ),
    ]
