# Generated by Django 4.2.27 on 2026-04-28 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0055_rename_sftpdropzone_accountjoblog_sftp_drop_zone"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccountJobLog",
        ),
    ]
