# Generated by Django 4.2.27 on 2026-04-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0056_delete_accountjoblog"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("completed_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "result_text",
                    models.TextField(blank=True, max_length=1000, null=True),
                ),
                ("path_and_filename", models.CharField(max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.account",
                    ),
                ),
                (
                    "accountjob",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.accountjob",
                    ),
                ),
                (
                    "sftp_drop_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenants.sftpdropzone",
                    ),
                ),
            ],
            options={
                "ordering": ["completed_datetime"],
            },
        ),
        migrations.CreateModel(
            name="AccountJobLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted", models.BooleanField(default=False)),
                ("message", models.TextField(blank=True, max_length=1000, null=True)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                (
                    "ingest_run",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tenants.ingestrun",
                    ),
                ),
            ],
            options={
                "ordering": ["created_datetime"],
            },
        ),
    ]
