# Generated by Django 5.2.10 on 2026-01-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ValueMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_code",
                    models.CharField(
                        help_text="Category or group of the mapping, e.g., 'fuel types'",
                        max_length=100,
                    ),
                ),
                (
                    "from_code",
                    models.CharField(
                        help_text="Original/source value/code", max_length=255
                    ),
                ),
                (
                    "to_code",
                    models.CharField(
                        help_text="Normalized/canonical value/code", max_length=255
                    ),
                ),
            ],
            options={
                "ordering": ["group_code", "from_code"],
                "unique_together": {("group_code", "from_code")},
            },
        ),
    ]
