# Generated by Django 4.2.27 on 2026-01-29 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ValueMappingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "convert_source_to_lowercase_first",
                    models.BooleanField(default=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ValueMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_code",
                    models.CharField(
                        help_text="Original/source value/code", max_length=255
                    ),
                ),
                (
                    "to_code",
                    models.CharField(
                        help_text="Normalized/canonical value/code", max_length=255
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mappings",
                        to="value_mappings.valuemappinggroup",
                    ),
                ),
            ],
            options={
                "unique_together": {("group", "from_code")},
            },
        ),
    ]
