# Generated by Django 5.2.10 on 2026-01-18 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("value_mappings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValueMappingGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="valuemapping",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="valuemapping",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="valuemapping",
            name="group",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mappings",
                to="value_mappings.valuemappinggroup",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="valuemapping",
            unique_together={("group", "from_code")},
        ),
        migrations.RemoveField(
            model_name="valuemapping",
            name="group_code",
        ),
    ]
