# Generated by Django 5.2.10 on 2026-01-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "value_mappings",
            "0002_valuemappinggroup_alter_valuemapping_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="valuemappinggroup",
            name="convert_source_to_lowercase_first",
            field=models.BooleanField(default=True),
        ),
    ]
