# Generated by Django 4.2.27 on 2026-03-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawCustomerVehicleData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=255)),
                (
                    "business_key_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("payload", models.JSONField()),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("source_row_number", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
