# Generated by Django 4.2.27 on 2026-03-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0037_remove_sftpdropzone_sftp_user"),
        ("raw_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawcustomervehicledata",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rawcustomervehicledata",
            name="row_hash",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rawcustomervehicledata",
            name="tenant",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="raw_customer_vehicle_data",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="rawcustomervehicledata",
            index=models.Index(
                fields=["tenant", "business_key_hash", "is_current"],
                name="raw_data_ra_tenant__ff2dfd_idx",
            ),
        ),
    ]
