# Generated by Django 4.2.27 on 2026-03-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("raw_data", "0002_rawcustomervehicledata_is_current_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawcustomervehicledata",
            name="last_seen_run_id",
            field=models.CharField(db_index=True, default="", max_length=19),
            preserve_default=False,
        ),
    ]
