# Generated by Django 4.2.27 on 2026-03-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("raw_data", "0003_rawcustomervehicledata_last_seen_run_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawcustomervehicledata",
            name="is_deleted_at_source",
            field=models.BooleanField(default=False),
        ),
    ]
