# Generated by Django 4.2.27 on 2026-04-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("raw_data", "0004_rawcustomervehicledata_is_deleted_at_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawRecallData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(max_length=255)),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("source_row_number", models.IntegerField(blank=True, null=True)),
                ("row_hash", models.CharField(max_length=64)),
                (
                    "business_key_hash",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("payload", models.JSONField()),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                ("is_current", models.BooleanField(default=False)),
                ("last_seen_run_id", models.CharField(db_index=True, max_length=19)),
                ("is_deleted_at_source", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["business_key_hash", "is_current"],
                        name="raw_data_ra_busines_a0265f_idx",
                    )
                ],
            },
        ),
    ]
