# Generated by Django 4.2.27 on 2026-04-17 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0051_remove_accountjob_filename_prefix"),
        ("raw_data", "0006_rawbookingdata"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="rawbookingdata",
            name="raw_data_ra_busines_ecc15f_idx",
        ),
        migrations.AddField(
            model_name="rawbookingdata",
            name="tenant",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="raw_booking_data",
                to="tenants.tenant",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="rawbookingdata",
            index=models.Index(
                fields=["tenant", "business_key_hash", "is_current"],
                name="raw_data_ra_tenant__0535b2_idx",
            ),
        ),
    ]
