# Generated by Django 4.2.27 on 2026-04-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "raw_data",
            "0007_remove_rawbookingdata_raw_data_ra_busines_ecc15f_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="rawbookingdata",
            name="debug_business_key",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="rawcustomervehicledata",
            name="debug_business_key",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="rawrecalldata",
            name="debug_business_key",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
