# Generated by Django 4.2.27 on 2026-04-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("raw_data", "0008_rawbookingdata_debug_business_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawbookingdata",
            name="debug_business_key",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawcustomervehicledata",
            name="debug_business_key",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rawrecalldata",
            name="debug_business_key",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
