"""
Django settings for palmtree_etl project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import sys
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(BASE_DIR / ".env")
TEMP_FILES_DIR = env("TEMP_FILES_DIR")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(@gg-007zxuwbwb8#klttm3fnai0&0&l!_$a@jh7aif5b!js)@'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "nested_admin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'core',
    'tenants',
    'canonical',
    'contracts',
    'value_mappings',
    'file_ingestion',
    'django_celery_results',

    "mptt",
    "sandbox",


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.middleware.DebugSessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'tenants.middleware.TenantResolutionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'palmtree_etl.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'tenants.context_processors.account_context',
                'tenants.context_processors.tenant_context',
                'palmtree_etl.context_processors.developer_quick_login_buttons',

            ],
        },
    },
]

WSGI_APPLICATION = 'palmtree_etl.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER_APP"),         # palmtree_app at runtime
        "PASSWORD": env("DB_PASSWORD_APP"),
        "HOST": env("DB_HOST", default="localhost"),
        "PORT": env("DB_PORT", default="5432"),
    },
    "migrate": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER_MIGRATE"),     # palmtree_migrate for migrations
        "PASSWORD": env("DB_PASSWORD_MIGRATE"),
        "HOST": env("DB_HOST", default="localhost"),
        "PORT": env("DB_PORT", default="5432"),
    },
    "readonly": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER_READONLY"),    # palmtree_readonly for BI/reporting
        "PASSWORD": env("DB_PASSWORD_READONLY"),
        "HOST": env("DB_HOST", default="localhost"),
        "PORT": env("DB_PORT", default="5432"),
    },
}

if "migrate" not in sys.argv and DATABASES["default"]["USER"] == env("DB_USER_MIGRATE"):
    raise RuntimeError("Do not use migrate user for normal runtime")

if "migrate" in sys.argv and "--database=migrate" not in sys.argv:
    raise RuntimeError("Use --database=migrate")

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

BASE_DIR = Path(__file__).resolve().parent.parent

INGESTION_INCOMING_DIR = BASE_DIR / "sftp_test_drop_folders/TENANT_000001/0_incoming"
INGESTION_RECEIVED_DIR = BASE_DIR / "sftp_test_drop_folders/TENANT_000001/1_received"
INGESTION_FAILED_DIR = BASE_DIR / "sftp_test_drop_folders/TENANT_000001/4_error"

CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_BACKEND = "django-db"

# After login, redirect here
LOGIN_REDIRECT_URL = "/"  
# After logout, redirect here
LOGOUT_REDIRECT_URL = "/login/" 

DEVELOPER_QUICK_LOGIN_BUTTONS = True

SFTP_HOST = env('SFTP_HOST')
SFTP_USER = env('SFTP_USER')
SFTP_PASSWORD = env('SFTP_PASSWORD')
SFTP_REMOTE_DIR = env('SFTP_REMOTE_DIR')

LOCAL_MASTER_KEY = env('LOCAL_MASTER_KEY')

