# Generated by Django 4.2.27 on 2026-03-02 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("file_ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestedfile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingestedfile",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ingestedfile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
