# Generated by Django 4.2.27 on 2026-03-01 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("short", models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("short", models.CharField(blank=True, max_length=8)),
                (
                    "marque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="global_data.marque",
                    ),
                ),
            ],
        ),
    ]
