# Generated by Django 4.2.27 on 2026-03-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "global_data",
            "0002_brand_created_at_brand_deleted_brand_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="is_fixture_safe",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marque",
            name="is_fixture_safe",
            field=models.BooleanField(default=False),
        ),
    ]
