# Generated by Django 4.2.27 on 2026-03-01 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("global_data", "0003_brand_is_fixture_safe_marque_is_fixture_safe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="is_fixture_safe",
        ),
        migrations.RemoveField(
            model_name="marque",
            name="is_fixture_safe",
        ),
    ]
