# Generated by Django 4.2.27 on 2026-01-29 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("value_mappings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanonicalField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("date", "Date"),
                            ("boolean", "Boolean"),
                            ("email", "Email"),
                            ("mapped_string", "Mapped string"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "normalisation",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Normalisation rules"
                    ),
                ),
                (
                    "format_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("email", "Email"),
                            ("postcode_uk", "UK Postcode"),
                        ],
                        default="none",
                        help_text="Semantic format (e.g. email, UK postcode)",
                        max_length=30,
                    ),
                ),
                ("is_pii", models.BooleanField(default=False)),
                ("requires_encryption", models.BooleanField(default=False)),
                ("required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CanonicalSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("contract", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SourceSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("system", models.CharField(max_length=50)),
                (
                    "canonical_schema",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_schema",
                        to="canonical.canonicalschema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TableData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "data",
                    models.JSONField(
                        default=list, help_text="Array of rows, first row is header"
                    ),
                ),
                (
                    "source_schema",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="table_data",
                        to="canonical.sourceschema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_field_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("order", models.PositiveIntegerField()),
                ("active", models.BooleanField(default=True)),
                (
                    "canonical_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="canonical.canonicalfield",
                    ),
                ),
                (
                    "source_schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_mappings",
                        to="canonical.sourceschema",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="canonicalfield",
            name="schema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="canonical.canonicalschema",
            ),
        ),
        migrations.AddField(
            model_name="canonicalfield",
            name="value_mapping_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional value mapping (e.g. fuel types)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="value_mappings.valuemappinggroup",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="canonicalfield",
            unique_together={("schema", "name")},
        ),
    ]
