# Generated by Django 5.2.10 on 2026-01-11 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CanonicalSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="CanonicalField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("date", "Date"),
                            ("boolean", "Boolean"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField()),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="canonical.canonicalschema",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("schema", "name")},
            },
        ),
        migrations.CreateModel(
            name="SourceSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("system", models.CharField(max_length=50)),
                (
                    "canonical_schema",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="source_schema",
                        to="canonical.canonicalschema",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_field_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("order", models.PositiveIntegerField()),
                ("active", models.BooleanField(default=True)),
                (
                    "canonical_field",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="canonical.canonicalfield",
                    ),
                ),
                (
                    "source_schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canonical.sourceschema",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TableData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "data",
                    models.JSONField(
                        default=list, help_text="Array of rows, first row is header"
                    ),
                ),
                (
                    "source_schema",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="table_data",
                        to="canonical.sourceschema",
                    ),
                ),
            ],
        ),
    ]
