# Generated by Django 5.2.10 on 2026-01-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalfield",
            name="format_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("email", "Email"),
                    ("postcode_uk", "UK Postcode"),
                ],
                default="none",
                help_text="Semantic format (e.g. email, UK postcode)",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="canonicalfield",
            name="is_pii",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="canonicalfield",
            name="normalisation",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Generic cleanup rules: trim, lowercase, null_if_empty, date_format, boolean_map",
            ),
        ),
        migrations.AddField(
            model_name="canonicalfield",
            name="requires_encryption",
            field=models.BooleanField(default=False),
        ),
    ]
