# Generated by Django 4.2.27 on 2026-02-01 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tabledata",
            options={"verbose_name": "Table data", "verbose_name_plural": "Table data"},
        ),
    ]
