# Generated by Django 5.2.10 on 2026-01-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0002_canonicalfield_format_type_canonicalfield_is_pii_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalschema",
            name="contract",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
