# Generated by Django 4.2.27 on 2026-02-02 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0007_rename_internal_location_code_location_short_and_more"),
        ("canonical", "0002_alter_tabledata_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_system_field_value", models.CharField(max_length=255)),
                (
                    "effective_from_date",
                    models.DateField(help_text="The date the mapping is valid from"),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_mappings",
                        to="tenants.account",
                    ),
                ),
                (
                    "mapped_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tenant_mappings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("account", "source_system_field_value", "effective_from_date")
                },
            },
        ),
    ]
