# Generated by Django 5.2.10 on 2026-01-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0003_canonicalschema_contract"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canonicalfield",
            name="normalisation",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Normalisation rules"
            ),
        ),
    ]
