# Generated by Django 4.2.27 on 2026-02-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0003_tenantmapping"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenantmapping",
            options={
                "verbose_name": "Tenant Code Mapping",
                "verbose_name_plural": "Tenant Code Mappings",
            },
        ),
        migrations.AddField(
            model_name="canonicalschema",
            name="requires_tenant_mapping",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="canonicalfield",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("string", "String"),
                    ("integer", "Integer"),
                    ("date", "Date"),
                    ("boolean", "Boolean"),
                    ("email", "Email"),
                    ("mapped_string", "Mapped string"),
                    ("tenant_mapping", "Tenant code mapping"),
                ],
                max_length=20,
            ),
        ),
    ]
