# Generated by Django 4.2.27 on 2026-02-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0004_alter_tenantmapping_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabledata",
            name="data",
            field=models.JSONField(
                blank=True, default=list, help_text="Array of rows, first row is header"
            ),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("desc", models.CharField(max_length=100)),
                ("one_or_many_source_files", models.BooleanField(default=False)),
                ("source_filename_pattern", models.CharField(max_length=50)),
                (
                    "canonical_schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canonical.canonicalschema",
                    ),
                ),
                (
                    "source_schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canonical.sourceschema",
                    ),
                ),
                (
                    "test_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="canonical.tabledata",
                    ),
                ),
            ],
        ),
    ]
