# Generated by Django 5.2.10 on 2026-01-17 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0004_alter_canonicalfield_normalisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldmapping",
            name="source_schema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_mappings",
                to="canonical.sourceschema",
            ),
        ),
    ]
