# Generated by Django 4.2.27 on 2026-02-03 21:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0005_alter_tabledata_data_job"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TenantMapping",
        ),
    ]
