# Generated by Django 5.2.10 on 2026-01-18 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0005_alter_fieldmapping_source_schema"),
        ("value_mappings", "0003_valuemappinggroup_convert_source_to_lowercase_first"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalfield",
            name="value_mapping_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional value mapping (e.g. fuel types)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="value_mappings.valuemappinggroup",
            ),
        ),
    ]
