# Generated by Django 4.2.27 on 2026-02-06 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0006_delete_tenantmapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="test_table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="canonical.tabledata",
                verbose_name="Test transformation with:",
            ),
        ),
    ]
