# Generated by Django 5.2.10 on 2026-01-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0006_canonicalfield_value_mapping_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="canonicalfield",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("string", "String"),
                    ("integer", "Integer"),
                    ("date", "Date"),
                    ("boolean", "Boolean"),
                    ("email", "Email"),
                    ("mapped_string", "Mapped string"),
                ],
                max_length=20,
            ),
        ),
    ]
