# Generated by Django 4.2.27 on 2026-02-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0007_alter_job_test_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldmapping",
            name="is_tenant_mapping_source",
            field=models.BooleanField(default=False),
        ),
    ]
