# Generated by Django 4.2.27 on 2026-02-08 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0008_fieldmapping_is_tenant_mapping_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="canonicalfield",
            name="is_pii",
        ),
        migrations.RemoveField(
            model_name="canonicalfield",
            name="requires_encryption",
        ),
        migrations.RemoveField(
            model_name="fieldmapping",
            name="canonical_field",
        ),
        migrations.AddField(
            model_name="canonicalfield",
            name="source_field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_mappings",
                to="canonical.fieldmapping",
            ),
        ),
        migrations.AddField(
            model_name="fieldmapping",
            name="is_pii",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fieldmapping",
            name="requires_encryption",
            field=models.BooleanField(default=False),
        ),
    ]
