# Generated by Django 4.2.27 on 2026-02-08 22:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0009_remove_canonicalfield_is_pii_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sourceschema",
            name="canonical_schema",
        ),
    ]
