# Generated by Django 4.2.27 on 2026-02-11 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0010_remove_sourceschema_canonical_schema"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fieldmapping",
            old_name="requires_encryption",
            new_name="requires_hashing",
        ),
    ]
