# Generated by Django 4.2.27 on 2026-02-11 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0011_rename_requires_encryption_fieldmapping_requires_hashing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fieldmapping",
            old_name="is_pii",
            new_name="pii_requires_encryption",
        ),
    ]
