# Generated by Django 4.2.27 on 2026-02-11 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0012_rename_is_pii_fieldmapping_pii_requires_encryption"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fieldmapping",
            old_name="requires_hashing",
            new_name="pii_requires_fingerprint",
        ),
    ]
