# Generated by Django 4.2.27 on 2026-02-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "canonical",
            "0013_rename_requires_hashing_fieldmapping_pii_requires_fingerprint",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldmapping",
            name="normalisation",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Raw Storage Normalisation Rules"
            ),
        ),
        migrations.AlterField(
            model_name="canonicalfield",
            name="normalisation",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Canonical Normalisation Rules"
            ),
        ),
    ]
