# Generated by Django 4.2.27 on 2026-02-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0014_fieldmapping_normalisation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldmapping",
            name="is_volatile",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="canonicalfield",
            name="format_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("email", "Email"),
                    ("postcode_full", "UK Postcode"),
                    ("postcode_area", "UK Postcode Area"),
                    ("postcode_district", "UK Postcode District"),
                    ("postcode_sector", "UK Postcode Sector"),
                ],
                default="none",
                help_text="Semantic format (e.g. email, UK postcode)",
                max_length=30,
            ),
        ),
    ]
