# Generated by Django 4.2.27 on 2026-02-18 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0015_fieldmapping_is_volatile_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="canonicalfield",
            unique_together={("schema", "source_field", "data_type", "format_type")},
        ),
    ]
