# Generated by Django 4.2.27 on 2026-03-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0017_canonicalfield_created_at_canonicalfield_deleted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldmapping",
            name="is_business_key",
            field=models.BooleanField(default=False),
        ),
    ]
