# Generated by Django 4.2.27 on 2026-04-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0018_fieldmapping_is_business_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceschema",
            name="raw_data_storage_model",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
