# Generated by Django 4.2.27 on 2026-04-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0019_sourceschema_raw_data_storage_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceschema",
            name="raw_data_storage_model",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
