# Generated by Django 4.2.27 on 2026-04-16 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0020_alter_sourceschema_raw_data_storage_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="canonicalschema",
            name="source_schema",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="canonical_schema",
                to="canonical.sourceschema",
            ),
        ),
    ]
