# Generated by Django 4.2.27 on 2026-04-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0021_canonicalschema_source_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="filename_prefix",
            field=models.CharField(default="tbc", max_length=100),
            preserve_default=False,
        ),
    ]
