# Generated by Django 4.2.27 on 2026-04-17 10:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0022_job_filename_prefix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="source_filename_pattern",
        ),
    ]
