# Generated by Django 4.2.27 on 2026-04-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("canonical", "0023_remove_job_source_filename_pattern"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="filename_prefix",
        ),
        migrations.AddField(
            model_name="sourceschema",
            name="filename_prefix",
            field=models.CharField(default="tbc", max_length=100),
            preserve_default=False,
        ),
    ]
